Repository metarhia/common, pull requests merged in 2019-04, with the labels that each got.

#255 Drop Node.js 6.x support
  .travis.yml
  package.json
Labels: compatibility, semver-major

#258 Expose AuthenticationStrength.compliance instead of strength
  lib/auth.js
  test/auth.js
Labels: enhancement, semver-major

#268 Update metatests to v0.6.5
  package-lock.json
  package.json
Labels: compatibility, semver-major

#270 Remove outdated common.inherits()
  lib/oop.js
Labels: compatibility, semver-major

#273 Remove deprecated functions and update documentation
  README.md
  lib/callbacks.js
  lib/id.js
  lib/network.js
  test/id.js
Labels: semver-major

#275 Add a changelog
  CHANGELOG.md
Labels: semver-minor

#278 Make collectWith return the provided object
  CHANGELOG.md
  lib/iterator.js
  test/iterator.js
Labels: semver-minor

#277 Implement Iterator.toObject
  CHANGELOG.md
  README.md
  lib/iterator.js
  test/iterator.js
Labels: enhancement, semver-minor

#276 Remove deprecate() and alias() functions
  CHANGELOG.md
  README.md
  lib/utilities.js
Labels: semver-major

#284 Change common.mergeObjects to pass key to merger
  CHANGELOG.md
  README.md
  lib/data.js
  test/data.js
Labels: semver-major

#285 Fix functions throwing when used on objects without prototype
  CHANGELOG.md
  lib/data.js
  test/data.js
Labels: bug, semver-patch

#281 Version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
