Repository metarhia/common, pull requests merged in 2019-03, with the labels that each got.

#256 Fix test script
  package.json
Labels: tests

#248 Version 1.3.0
  package-lock.json
  package.json
Labels: release, semver-minor

#261 Add password auth tests
  lib/auth.js
  test/auth.js
Labels: semver-minor

#266 Remove metasync dependency to avoid issues with circular `require()`s
  lib/fs.js
  package-lock.json
  package.json
Labels: semver-patch
